version: '3.9'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        volumes:
            - .:/var/www
        environment:
            - APP_ENV=${APP_ENV}
        depends_on:
            - db
        networks:
            - app-network

    nginx:
        image: nginx:alpine
        container_name: nginx_server
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/${APP_ENV}.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - app-network

    db:
        image: mysql:8.0
        container_name: mysql_db
        restart: unless-stopped
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-${DB_PASSWORD}}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        ports:
            - "3306:3306"
        networks:
            - app-network

volumes:
    dbdata:

networks:
    app-network:
        driver: bridge
